---
title: "Pheno_selection"
author: "Weier Guo"
date: "5/4/2022"
output: html_document
---

## Introduction 
Investigate 68 phenotypes to select segregated ones for 500 individuals. 

## Working Process ##
### Import Data ###
#### library ####
```{r}
library(tidyverse)
library(ggplot2)
```

#### dataset ####
**headers**
```{r}
header <- readLines("../input/pheno_output_table_blup_20220428.txt",n=1)
header <- header %>%
  str_split("\t") %>%
  unlist()
```

**data import**
```{r}
pheno <- read_tsv("../input/pheno_output_table_blup_20220428.txt",col_names = header,comment = "Old")
pheno
```

**Cross Type**
```{r}
headerTP <- readLines("../input/XXX_GWR_IFG_FOrWeier.txt",n=1)
headerTP <- headerTP %>%
  str_split("\t") %>%
  unlist()

crosstype <- read_tsv("../input/XXX_GWR_IFG_FOrWeier.txt", col_names = headerTP, comment = "Old") %>%
  select(Old.Name,CrossType)
crosstype
```

### combine two data frames ###
```{r}
pheno <- left_join(pheno,crosstype, by="Old.Name")
pheno
```


### Remove IFG samples ###
```{r}
pheno <- pheno %>%
  filter(CrossType == "GWR") 
pheno
```

### plot all phenotypes ###
```{r}
pl <- ggplot(pheno,aes(x = pheno[[21]])) +
  geom_histogram() +
  ggtitle(colnames(pheno[21])) 
pl
ggsave("../output/BiomassPheno20_20220511.png")
```




### Sort phenotypes with less NA to more NA ###
```{r}
pheno.sum <- as.data.frame(matrix(header[-1], nrow = 68))
data.n <- c()
for (i in 2:69) {
  noNA <- !is.na(pheno[[i]])
  noNA <- noNA[noNA == TRUE]
  data.n <- c(data.n, length(noNA))
}
pheno.sum <- cbind(pheno.sum,data.n) %>%
  arrange(desc(data.n))
pheno.sum
```

### Plot ###
```{r}
pheno %>%
  ggplot(aes(x=1,y=Blup_Transfo_bud_burst_y1_v2)) +
  geom_violin() +
  geom_point(alpha=0.6)
```

### Check the maximum and minumn sample IDs in candidate phenotypes ###
```{r}
pheno <- pheno %>%
  arrange(desc(Blup_Transfo_AUC_bud_burst_y1_y2)) %>%
  select(Old.Name,Blup_Transfo_AUC_bud_burst_y1_y2,Blup_Transfo_bud_burst_y1_y2,Blup_Transfo_time_serie_bud_burst_y1_y2, Blup_Transfo_bud_burst_y1_y2_v2,Blup_Transfo_time_serie_bud_burst_y1_y2_v2, everything())
pheno
```

### save selected GWR files ###
```{r}
write.csv(pheno,"../input/Pheno_pre_GWR_20220506.csv")
```


